# Use UBI
FROM registry.access.redhat.com/ubi9/ubi@sha256:ed84f34cd929ea6b0c247b6daef54dd79602804a32480a052951021caf429494

# Install httpd
RUN dnf install -y httpd

# Copy the config
COPY config/* /etc/httpd/conf

# Copy the website
COPY website/* /var/www/html/

# Expose Port
EXPOSE 8080

# Start httpd
CMD ["httpd", "-DFOREGROUND"]
